//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterpolationExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class GammaRay
    {
        public int id { get; set; }
        public System.DateTime datastamp { get; set; }
        public double MD { get; set; }
        public double GRBX { get; set; }
    }
}
